export const Provinces = [
  { value: "Kurdistan", title: "کردستان" },
  { value: "Isfahan", title: "اصفهان" },
  { value: "Tehran", title: "تهران" },
  { value: "Semnan", title: "سمنان" },
  { value: "Kashan", title: "کاشان" },
  { value: "Hormozgan", title: "هرمزگان" },
  { value: "Fars", title: "فارس" },
  { value: "Khuzestan", title: "خوزستان" },
  { value: "Lorestan", title: "لرستان" },
  { value: "Azerbaijan", title: "آذربایجان" },
  { value: "Razavi-Khorasan", title: "خراسان رضویی" },
  { value: "Kerman", title: "کرمان" },
  { value: "Markazi", title: "مرکزی" },
  { value: "Mazandaran", title: "مازنداران" },
  { value: "Sistan-and-Baluchestan", title: "سیستان و بلوچستان" },
  { value: "South-Khorasan", title: "خراسان جنوبی" },
  { value: "North-Khorasan", title: "خراسان شمالی" },
  { value: "Yazd", title: "یزد" },
  { value: "Ilam", title: "ایلام" },
  { value: "Hamadan", title: "همدان" },
  { value: "Golestan", title: "گلستان" },
  { value: "Gilan", title: "گیلان" },
  { value: "Bushehr", title: "بوشهر" },
  { value: "Alborz", title: "البرز" },
  { value: "Ardabil", title: "اردبیل" },
  { value: "Qazvin", title: "قزوین" },
  { value: "Qom", title: "قم" },
];
